/**
  This file is autogenerated by indexr.
  Check this file into source control.
  Do not edit this file.
  For more information: http://github.com/ryardley/indexr
**/
import modules from './modules';
export default [
  modules
];
/** End autogenerated content **/
