/**
  This file is autogenerated by indexr.
  Check this file into source control.
  Do not edit this file.
  For more information: http://github.com/ryardley/indexr
**/
import args from './args/cliflags.js';
import exts from './exts/cliflags.js';
import file from './file/cliflags.js';
import imports from './imports/cliflags.js';
import moduleFolders from './moduleFolders/cliflags.js';
import submodules from './submodules/cliflags.js';
import template from './template/cliflags.js';
import watch from './watch/cliflags.js';
export default [
  args,
  exts,
  file,
  imports,
  moduleFolders,
  submodules,
  template,
  watch
];
/** End autogenerated content **/
