import camelCase from 'camelcase';
import {
  truthy,
} from './utils';

export const headerComment = () => `/**
  This file is autogenerated by indexr.
  Check this file into source control.
  Do not edit this file.
  For more information: http://github.com/ryardley/indexr
**/`;

export const footerComment = () => '/** End autogenerated content **/';

export const localModuleName = (module) => camelCase(module.split('/')[0]);

export const moduleArray = (modules) => {
  const localModules = modules.filter(truthy).map(localModuleName);
  return `[
  ${localModules.join(`,\n  `)}
]`;
};
